In [1]:
a = [1,2,3]
type(a)

list

In [5]:
[1,2,4]*3

[1, 2, 4, 1, 2, 4, 1, 2, 4]

In [15]:
list(range(1,4))

[1, 2, 3]

In [41]:
3**2

9

In [45]:
a= list(range(1000000))
b= list(range(1000000))

In [47]:
%time
s = 0
for i in range(len(a)):
    s= s+ a[i]*b[i]
print(s)

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 5.96 µs
333332833333500000


In [8]:
import numpy as np

In [19]:
np.arange(1,4)

array([1, 2, 3])

In [48]:
a= np.arange(5000000)
b= np.arange(5000000)

In [49]:
%time
c = a.dot(b)
#print(c)

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 10.3 µs


In [10]:
a.shape

(10000000,)

In [11]:
b.shape

(10000000,)

In [54]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
a.dot(a.T)

array([[14, 32],
       [32, 77]])

In [57]:
c = a.dot(a.T)

In [58]:
c

array([[14, 32],
       [32, 77]])

In [59]:
type(c)

numpy.ndarray

In [64]:
c[0,1] = 10
c

array([[10, 10],
       [32, 77]])

In [66]:
c.sum(axis = 1)

array([ 20, 109])

In [70]:
c[0,0] = 90
c

array([[90, 10],
       [32, 77]])

In [71]:
np.sin(c)

array([[ 0.89399666, -0.54402111],
       [ 0.55142668,  0.99952016]])

In [74]:
a = np.array([1,2,3])
b = np.array([2,2,2])
a/b

array([0.5, 1. , 1.5])

In [75]:
a**2

array([1, 4, 9])

In [76]:
## 2d arrays

In [77]:
c = np.array([[12,  3,  4,  5,  5],
       [ 4,  3,  4,  5,  6],
       [ 6,  4,  5,  6,  3],
       [ 6,  4,  6,  7,  4],
       [ 6,  4,  5,  7,  8]])
c

array([[12,  3,  4,  5,  5],
       [ 4,  3,  4,  5,  6],
       [ 6,  4,  5,  6,  3],
       [ 6,  4,  6,  7,  4],
       [ 6,  4,  5,  7,  8]])

In [79]:
c[0][0]

12

In [86]:
c[1:4,1:4]

array([[3, 4, 5],
       [4, 5, 6],
       [4, 6, 7]])

In [88]:
a = [0,1,2]
c[a,a]

array([12,  3,  5])

In [89]:
c[0:-1:2,0:-2:2]

array([[12,  4],
       [ 6,  5]])

In [90]:
c

array([[12,  3,  4,  5,  5],
       [ 4,  3,  4,  5,  6],
       [ 6,  4,  5,  6,  3],
       [ 6,  4,  6,  7,  4],
       [ 6,  4,  5,  7,  8]])

In [91]:
c[c>5]

array([12,  6,  6,  6,  6,  6,  7,  6,  7,  8])

In [92]:
c>5

array([[ True, False, False, False, False],
       [False, False, False, False,  True],
       [ True, False, False,  True, False],
       [ True, False,  True,  True, False],
       [ True, False, False,  True,  True]])

In [93]:
a = [1,2,3,5,6]
a[2]

3

In [97]:
a = np.array([1,2,3,5,6])
b = [0,0,1,0,0]
a[b]

array([1, 1, 2, 1, 1])

In [98]:
a = np.array([1,2,3,5,6])
b = np.array([0,0,1,0,0],dtype = bool)
a[b]

array([3])

In [99]:
## Broadcasting

In [100]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a.shape)
print(b.shape)

(3,)
(3,)


In [101]:
a.dot(b)

20

In [102]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,3],[4,5],[6,4]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
b

array([[1, 3],
       [4, 5],
       [6, 4]])

In [104]:
a.dot(b)

array([[27, 25],
       [60, 61]])

In [105]:
b.dot(a)

array([[13, 17, 21],
       [24, 33, 42],
       [22, 32, 42]])

In [106]:
np.matmul(a,b)

array([[27, 25],
       [60, 61]])

In [107]:
a = np.array([1,2,3])
b = np.array([3,5,6])
print(a.shape)
print(b.shape)

(3,)
(3,)


In [108]:
a1 = a.reshape(3,1)
b1 = b.reshape(3,1)

In [109]:
print(a1.shape)
print(b1.shape)

(3, 1)
(3, 1)


In [111]:
a1

array([[1],
       [2],
       [3]])

In [112]:
b1

array([[3],
       [5],
       [6]])

In [113]:
a1+b1

array([[4],
       [7],
       [9]])

In [114]:
b3 = b.reshape(1,3)
b3

array([[3, 5, 6]])

In [118]:
a1,print(a1.shape)

(3, 1)


(array([[1],
        [2],
        [3]]),
 None)

In [119]:
b3,print(b3.shape)

(1, 3)


(array([[3, 5, 6]]), None)

In [120]:
a1+b3

array([[4, 6, 7],
       [5, 7, 8],
       [6, 8, 9]])